### ISSUE TITLE
Device restart and shutdown option

### ISSUE THREAD

**Issue by bikeebh** [electricbubble/gidevice-cli#13]
This repository is interesting for iOS devices

@electricbubble is there any command for restart and shutdown the iOS deivce.

**Comment by electricbubble** [comment]
> https://github.com/libimobiledevice/libimobiledevice/blob/25059d4c7d75e03aab516af2929d7c6e6d4c17de/tools/idevicediagnostics.c

I think it's possible

But I'm sorry that I haven't had enough time to implement this feature recently

**Comment by bikeebh** [comment]
thanks @electricbubble above link work for me
