### ISSUE TITLE
wda可以打包成ipa来使用吗？这样做的目的是为了绕开xcode设备数量限制吗？

### ISSUE THREAD

**Issue by NoneTypeCoder** [electricbubble/gidevice-cli#18]

**Comment by electricbubble** [comment]
`wda` 可以打包成 `ipa`

但实际上并不能绕开设备数量限制

**Comment by NoneTypeCoder** [comment]
将wda打包成ipa后 安装wda不是就不用通过xcode来build了是吗？  这样不算绕过 使用xcode来build wda的设备数量限制吗？ 是不是我有什么地方理解错了
