### ISSUE TITLE
Requesting to show console logs only when added --debug

### ISSUE THREAD

**Issue by krishtoautomate** [electricbubble/gidevice-cli#4]
Requesting to show logs only when executed command with argument --debug

gidevice -u $UDID  xctest com.facebook.WebDriverAgentRunner.xctrunner --debug

**Comment by electricbubble** [comment]
`XCTest` output is the same as `Xcode`

I just think it is much more useful

**Comment by krishtoautomate** [comment]
it will be great to have two options - with debug logs and without logs(just get a message connected url)

**Comment by electricbubble** [comment]
if didn't use to launch `WDA`?
nothing to display?

**Comment by electricbubble** [comment]
I think that's good
> [v0.4.2](https://github.com/electricbubble/gidevice-cli/releases/tag/v0.4.2)

```bash
$ gidevice xctest com.leixipaopao.WebDriverAgentRunner.xctrunner --contains="ServerURLHere->" --contains="Running tests..." --contains="Built at"

2021-04-28 23:15:56.229402+0800 WebDriverAgentRunner-Runner[2436:498709] Running tests...
2021-04-28 23:15:57.709613+0800 WebDriverAgentRunner-Runner[2436:498709] Built at Apr 24 2021 00:16:35
2021-04-28 23:15:57.719480+0800 WebDriverAgentRunner-Runner[2436:498709] ServerURLHere->http://192.168.1.14:8100<-ServerURLHere

```

**Comment by krishtoautomate** [comment]
works perfect. thanks
