### ISSUE TITLE
Change port in wda with cli is not working

### ISSUE THREAD

**Issue by krishtoautomate** [electricbubble/gidevice-cli#8]
below command is not changing the port and still selecting default port 8100

gidevice -u $UDID xctest com.facebook.WebDriverAgentRunner.xctrunner —port 8200 —mjpeg-server-port 9200

**Comment by electricbubble** [comment]
[v0.4.3](https://github.com/electricbubble/gidevice-cli/releases/tag/v0.4.3)

```bash
gidevice xctest com.facebook.WebDriverAgentRunner.xctrunner --env=USE_PORT=8200 --env=MJPEG_SERVER_PORT=9200
```

**Comment by krishtoautomate** [comment]
works.
Thank you so much.

`gidevice -u $UDID xctest com.facebook.WebDriverAgentRunner.xctrunner -c "ServerURLHere" -e USE_PORT=8200`
